-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 21:21:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema corona 
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `corona ` ;

-- -----------------------------------------------------
-- Schema corona 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corona ` DEFAULT CHARACTER SET utf8 ;
USE `corona ` ;

-- -----------------------------------------------------
-- Table `corona `.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`users` ;

CREATE TABLE IF NOT EXISTS `corona `.`users` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`Actores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`Actores` ;

CREATE TABLE IF NOT EXISTS `corona `.`Actores` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  `e-Mail` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`POV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`POV` ;

CREATE TABLE IF NOT EXISTS `corona `.`POV` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Cargos` VARCHAR(45) NULL,
  `e-Mail` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `RazonSocial` VARCHAR(45) NULL,
  `Establecimiento` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`events` ;

CREATE TABLE IF NOT EXISTS `corona `.`events` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `date` TIMESTAMP NULL,
  `Gerente` INT NOT NULL,
  `Responsable` INT NOT NULL,
  `Establecimiento` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Cajas Negociadas` VARCHAR(45) NULL,
  `Tipo de promocion` VARCHAR(45) NULL,
  `Invitaciones` VARCHAR(45) NULL,
  `cover` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `Creador` VARCHAR(45) NOT NULL,
  `create_time` VARCHAR(45) NULL,
  `update_time` VARCHAR(45) NULL,
  `editor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_events_Actores`
    FOREIGN KEY (`Gerente`)
    REFERENCES `corona `.`Actores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_Actores1`
    FOREIGN KEY (`Responsable`)
    REFERENCES `corona `.`Actores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_POV1`
    FOREIGN KEY (`Establecimiento`)
    REFERENCES `corona `.`POV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`Creador`)
    REFERENCES `corona `.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_users2`
    FOREIGN KEY (`editor`)
    REFERENCES `corona `.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_events_Actores_idx` ON `corona `.`events` (`Gerente` ASC) VISIBLE;

CREATE INDEX `fk_events_Actores1_idx` ON `corona `.`events` (`Responsable` ASC) VISIBLE;

CREATE INDEX `fk_events_POV1_idx` ON `corona `.`events` (`Establecimiento` ASC) VISIBLE;

CREATE INDEX `fk_events_users1_idx` ON `corona `.`events` (`Creador` ASC) VISIBLE;

CREATE INDEX `fk_events_users2_idx` ON `corona `.`events` (`editor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `corona `.`Logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`Logs` ;

CREATE TABLE IF NOT EXISTS `corona `.`Logs` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`experiences` ;

CREATE TABLE IF NOT EXISTS `corona `.`experiences` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`dj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`dj` ;

CREATE TABLE IF NOT EXISTS `corona `.`dj` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`List_Basico_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`List_Basico_type` ;

CREATE TABLE IF NOT EXISTS `corona `.`List_Basico_type` (
  `id` INT NOT NULL,
  `events_id` INT NOT NULL,
  `experience` INT NOT NULL,
  `dj_id` INT NOT NULL,
  `dj_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_List_3_type_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `corona `.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Basico_type_experiences1`
    FOREIGN KEY (`experience`)
    REFERENCES `corona `.`experiences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Basico_type_dj1`
    FOREIGN KEY (`dj_id`)
    REFERENCES `corona `.`dj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Basico_type_dj2`
    FOREIGN KEY (`dj_id1`)
    REFERENCES `corona `.`dj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_List_3_type_events1_idx` ON `corona `.`List_Basico_type` (`events_id` ASC) VISIBLE;

CREATE INDEX `fk_List_Basico_type_experiences1_idx` ON `corona `.`List_Basico_type` (`experience` ASC) VISIBLE;

CREATE INDEX `fk_List_Basico_type_dj1_idx` ON `corona `.`List_Basico_type` (`dj_id` ASC) VISIBLE;

CREATE INDEX `fk_List_Basico_type_dj2_idx` ON `corona `.`List_Basico_type` (`dj_id1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `corona `.`International_Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`International_Artist` ;

CREATE TABLE IF NOT EXISTS `corona `.`International_Artist` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`List_Flag_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`List_Flag_type` ;

CREATE TABLE IF NOT EXISTS `corona `.`List_Flag_type` (
  `id` INT NOT NULL,
  `events_id` INT NOT NULL,
  `experiences_id` INT NOT NULL,
  `experience2` INT NOT NULL,
  `experience3` INT NOT NULL,
  `International_Artist_id` INT NOT NULL,
  `dj_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_List_Flag_type_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `corona `.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Flag_type_experiences1`
    FOREIGN KEY (`experiences_id`)
    REFERENCES `corona `.`experiences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Flag_type_experiences2`
    FOREIGN KEY (`experience2`)
    REFERENCES `corona `.`experiences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Flag_type_experiences3`
    FOREIGN KEY (`experience3`)
    REFERENCES `corona `.`experiences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Flag_type_International_Artist1`
    FOREIGN KEY (`International_Artist_id`)
    REFERENCES `corona `.`International_Artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Flag_type_dj1`
    FOREIGN KEY (`dj_id`)
    REFERENCES `corona `.`dj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_List_Flag_type_events1_idx` ON `corona `.`List_Flag_type` (`events_id` ASC) VISIBLE;

CREATE INDEX `fk_List_Flag_type_experiences1_idx` ON `corona `.`List_Flag_type` (`experiences_id` ASC) VISIBLE;

CREATE INDEX `fk_List_Flag_type_experiences2_idx` ON `corona `.`List_Flag_type` (`experience2` ASC) VISIBLE;

CREATE INDEX `fk_List_Flag_type_experiences3_idx` ON `corona `.`List_Flag_type` (`experience3` ASC) VISIBLE;

CREATE INDEX `fk_List_Flag_type_International_Artist1_idx` ON `corona `.`List_Flag_type` (`International_Artist_id` ASC) VISIBLE;

CREATE INDEX `fk_List_Flag_type_dj1_idx` ON `corona `.`List_Flag_type` (`dj_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `corona `.`nacional_Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`nacional_Artist` ;

CREATE TABLE IF NOT EXISTS `corona `.`nacional_Artist` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona `.`List_Top_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corona `.`List_Top_type` ;

CREATE TABLE IF NOT EXISTS `corona `.`List_Top_type` (
  `id` INT NOT NULL,
  `events_id` INT NOT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `experience1` INT NOT NULL,
  `experience2` INT NOT NULL,
  `nacional_Artist_id` INT NOT NULL,
  `dj_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_List_Top_type_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `corona `.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Top_type_experiences1`
    FOREIGN KEY (`experience1`)
    REFERENCES `corona `.`experiences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Top_type_experiences2`
    FOREIGN KEY (`experience2`)
    REFERENCES `corona `.`experiences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Top_type_nacional_Artist1`
    FOREIGN KEY (`nacional_Artist_id`)
    REFERENCES `corona `.`nacional_Artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Top_type_dj1`
    FOREIGN KEY (`dj_id`)
    REFERENCES `corona `.`dj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_List_Top_type_events1_idx` ON `corona `.`List_Top_type` (`events_id` ASC) VISIBLE;

CREATE INDEX `fk_List_Top_type_experiences1_idx` ON `corona `.`List_Top_type` (`experience1` ASC) VISIBLE;

CREATE INDEX `fk_List_Top_type_experiences2_idx` ON `corona `.`List_Top_type` (`experience2` ASC) VISIBLE;

CREATE INDEX `fk_List_Top_type_nacional_Artist1_idx` ON `corona `.`List_Top_type` (`nacional_Artist_id` ASC) VISIBLE;

CREATE INDEX `fk_List_Top_type_dj1_idx` ON `corona `.`List_Top_type` (`dj_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
